### ISSUE TITLE
Webserver initilization

### ISSUE THREAD

**Issue by raavioli** [konosp/dbt-airflow-docker-compose#3]
while composing the image i am having multiple issues while initializing the image.

1) is there a particular version of image that you are working with the dockerfile does not mention that, may be thats where the problem starts while composing
2) scripts_airflow/init.sh DB connection works fine but i suppose the order of initialization or airflow web sever is probably where the issue is 
Here is one of the error log while executing  from init.sh file 
rm: cannot remove '/airflow/airflow-webserver.pid': No such file or directory
i tried changing the path to /run/airflow/ folder no avail it does pick up this change 

2) May be its dependent on 1 
so the correct order will be 
db 
web server 
airflow initdb
scheduler
workers

initdb will create all tables airflow will use and thats the reason why its erroring out that its not created because the scheduler was first 

```

The above exception was the direct cause of the following exception:
airflow_1           |
airflow_1           | Traceback (most recent call last):
airflow_1           |   File "/usr/local/bin/airflow", line 8, in <module>
airflow_1           |     sys.exit(main())
airflow_1           |   File "/usr/local/lib/python3.7/site-packages/airflow/__main__.py", line 40, in main
airflow_1           |     args.func(args)
airflow_1           |   File "/usr/local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
airflow_1           |     return func(*args, **kwargs)
airflow_1           |   File "/usr/local/lib/python3.7/site-packages/airflow/utils/cli.py", line 89, in wrapper
airflow_1           |     return f(*args, **kwargs)
airflow_1           |   File "/usr/local/lib/python3.7/site-packages/airflow/cli/commands/scheduler_command.py", line 63, in scheduler
airflow_1           |     job.run()
airflow_1           |   File "/usr/local/lib/python3.7/site-packages/airflow/jobs/base_job.py", line 233, in run
airflow_1           |     session.commit()
airflow_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1046, in commit
airflow_1           |     self.transaction.commit()
airflow_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 504, in commit
airflow_1           |     self._prepare_impl()
airflow_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 483, in _prepare_impl
airflow_1           |     self.session.flush()
airflow_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2540, in flush
airflow_1           |     self._flush(objects)
airflow_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2682, in _flush
airflow_1           |     transaction.rollback(_capture_exception=True)
airflow_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
airflow_1           |     with_traceback=exc_tb,
airflow_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
airflow_1           |     raise exception
airflow_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2642, in _flush
airflow_1           |     flush_context.execute()
airflow_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
airflow_1           |     rec.execute(self)
airflow_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
airflow_1           |     uow,
airflow_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
airflow_1           |     insert,
airflow_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1136, in _emit_insert_statements
airflow_1           |     statement, params
airflow_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
airflow_1           |     return meth(self, multiparams, params)
airflow_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
airflow_1           |     return connection._execute_clauseelement(self, multiparams, params)
airflow_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
airflow_1           |     distilled_params,
airflow_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
airflow_1           |     e, statement, parameters, cursor, context
airflow_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
airflow_1           |     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
airflow_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
airflow_1           |     raise exception
airflow_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
airflow_1           |     cursor, statement, parameters, context
airflow_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute
airflow_1           |     cursor.execute(statement, parameters)
airflow_1           | sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "job" does not exist
airflow_1           | LINE 1: INSERT INTO job (dag_id, state, job_type, start_date, end_da...
airflow_1           |                     ^
airflow_1           |
airflow_1           | [SQL: INSERT INTO job (dag_id, state, job_type, start_date, end_date, latest_heartbeat, executor_class, hostname, unixname) VALUES (%(dag_id)s, %(state)s, %(job_type)s, %(start_date)s, %(end_date)s, %(latest_heartbeat)s, %(executor_class)s, %(hostname)s, %(unixname)s) RETURNING job.id]
airflow_1           | [parameters: {'dag_id': None, 'state': 'running', 'job_type': 'SchedulerJob', 'start_date': datetime.datetime(2020, 12, 29, 11, 22, 6, 743607, tzinfo=Timezone('UTC')), 'end_date': None, 'latest_heartbeat': datetime.datetime(2020, 12, 29, 11, 22, 6, 743712, tzinfo=Timezone('UTC')), 'executor_class': 'LocalExecutor', 'hostname': '28a919cef867', 'unixname': 'root'}]
airflow_1           | (Background on this error at: http://sqlalche.me/e/13/f405)
postgres-airflow_1  | 2020-12-29 11:22:13.260 UTC [84] ERROR:  relation "log" does not exist at character 13
postgres-airflow_1  | 2020-12-29 11:22:13.260 UTC [84] STATEMENT:  INSERT INTO log (dttm, dag_id, task_id, event, execution_date, owner, extra) VALUES ('2020-12-29T11:22:13.193291+00:00'::timestamptz, NULL, NULL, 'cli_webserver', NULL, 'root', '{"host_name": "28a919cef867", "full_command": "[''/usr/local/bin/airflow'', ''webserver'']"}') RETURNING log.id
airflow_1           | [2020-12-29 11:22:13,269] {cli_action_loggers.py:105} WARNING - Failed to log action with (psycopg2.errors.UndefinedTable) relation "log" does not exist
airflow_1           | LINE 1: INSERT INTO log (dttm, dag_id, task_id, event, execution_dat...
airflow_1           |                     ^
airflow_1           |
airflow_1           | [SQL: INSERT INTO log (dttm, dag_id, task_id, event, execution_date, owner, extra) VALUES (%(dttm)s, %(dag_id)s, %(task_id)s, %(event)s, %(execution_date)s, %(owner)s, %(extra)s) RETURNING log.id]
airflow_1           | [parameters: {'dttm': datetime.datetime(2020, 12, 29, 11, 22, 13, 193291, tzinfo=Timezone('UTC')), 'dag_id': None, 'task_id': None, 'event': 'cli_webserver', 'execution_date': None, 'owner': 'root', 'extra': '{"host_name": "28a919cef867", "full_command": "[\'/usr/local/bin/airflow\', \'webserver\']"}'}]
airflow_1           | (Background on this error at: http://sqlalche.me/e/13/f405)

```
Any pointers will be appreciated

**Comment by raavioli** [comment]
also while updating /scripts/airflow/init.sh 


used the error response from below 
```
airflow command error: argument GROUP_OR_COMMAND: `airflow upgradedb` command, has been removed, please use `airflow db upgrade`, see help above.

```

**Comment by konosp** [comment]
Hi @RaviHindocha ,

thanks for flagging these issues. Not sure how never got spotted before. There were a few things that needed updates:
- Apache released version 2 of Airflow which does not have full backwards compatibility. Hence during the installation, I have set the version of Airflow to 1.10.14  - https://github.com/apache/airflow/releases/tag/1.10.14
- Airflow requires a random security key during init process - again, I am not sure when this was updated but looks to work now.
- Have modified the shell script to not fail if the webserver.pid file is not present. 

Please try again with the updates and let me know how it looks.

cheers!

**Comment by konosp** [comment]
Closing this issue. Please let me know if the issues persist.

**Comment by raavioli** [comment]
@konosp thanks for the update, it works like a charm now, will play around with dags and dbt will let you know if anything
